# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160416_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('caption', models.CharField(max_length=200)),
                ('catagory', models.CharField(max_length=200)),
            ],
        ),
    ]
