# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='platform',
            field=models.CharField(default='youtube', max_length=200),
        ),
    ]
